import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import $ from jquery
import '../calculator.js'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Glory Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
        <div className="calculator">
  <p>Glory Calculator</p>
  <div className="calc-row">
    <div className="screen">0123456789</div>
  </div>
  
  <div className="calc-row">
    <div className="button">C</div><div className="button">CE</div><div className="button backspace">back</div><div className="button plus-minus">+/-</div><div className="button">%</div>
  </div>
  
  <div className="calc-row">
    <div className="button">7</div><div className="button">8</div><div className="button">9</div><div className="button divice">/</div><div className="button root">sqrt</div>
  </div>
  
  <div className="calc-row">
    <div className="button">4</div><div className="button">5</div><div className="button">6</div><div className="button multiply">*</div><div className="button inverse">1/x</div>
  </div>
  
  <div className="calc-row">
    <div className="button">1</div><div className="button">2</div><div className="button">3</div><div className="button">-</div><div className="button pi">pi</div>
  </div>
  
  <div className="calc-row">
    <div className="button zero">0</div><div className="button decimal">.</div><div className="button">+</div><div className="button equal">=</div>
  </div>
</div>
        </div>
      </main>
    </>
  )
}
